"""Cross-signal validator that uses a DIFFERENT evaluation method than fix generation.

Breaks circular validation by ensuring:
- Heuristic-generated fixes are validated by LLM judge
- LLM-generated fixes are validated by structural checks
- Both paths provide independent confirmation that fixes improved quality
"""

import logging
from typing import Dict, Any, List, Optional

from ..models import QualityReport, DimensionScore
from .models import QualityAppliedFix, QualityValidationResult
from .n8n_schema import validate_fix_against_n8n_schema

logger = logging.getLogger(__name__)


class QualityFixValidator:
    """Validates quality fixes using cross-signal evaluation.

    When a fix is generated by heuristics (keyword-targeted), it's validated
    by LLM semantic evaluation. When generated by LLM, it's validated by
    structural checks. This prevents circular validation where the same
    scoring algorithm both generates and approves fixes.
    """

    def __init__(self, validation_mode: str = "cross_signal"):
        """
        Args:
            validation_mode: "cross_signal" (default), "heuristic_only", or "llm_only"
        """
        self.validation_mode = validation_mode
        self._assessor = None
        self._judge = None

    def _get_assessor(self):
        """Lazy-load the quality assessor."""
        if self._assessor is None:
            from .. import QualityAssessor
            self._assessor = QualityAssessor(use_llm_judge=False)
        return self._assessor

    def _get_judge(self):
        """Lazy-load the LLM judge (only if API key is configured)."""
        if self._judge is None:
            try:
                from ...evals.llm_judge import LLMJudge, JudgeModel
                judge = LLMJudge(model=JudgeModel.CLAUDE_HAIKU)
                if not judge.api_key:
                    self._judge = False  # No API key → unavailable
                else:
                    self._judge = judge
            except Exception:
                self._judge = False  # Mark as unavailable
        return self._judge if self._judge is not False else None

    def validate(
        self,
        applied_fix: QualityAppliedFix,
        original_report: QualityReport,
    ) -> QualityValidationResult:
        """Validate a single applied fix using cross-signal evaluation."""
        if self.validation_mode == "cross_signal":
            result = self._cross_signal_validate(applied_fix, original_report)
        elif self.validation_mode == "llm_only":
            result = self._llm_validation(applied_fix, original_report)
        else:
            result = self._heuristic_validation(applied_fix, original_report)

        # Non-blocking behavioral validation after structural pass
        if result.success:
            behavioral_ok = self._behavioral_validate(
                applied_fix,
                applied_fix.original_state,
                applied_fix.modified_state,
                original_report,
            )
            if not behavioral_ok:
                logger.warning(
                    "Behavioral validation failed for fix %s (dimension=%s) — allowing fix anyway",
                    applied_fix.fix_id,
                    applied_fix.dimension,
                )
            result.details["behavioral_validation"] = behavioral_ok

        return result

    def validate_all(
        self,
        applied_fixes: List[QualityAppliedFix],
        original_report: QualityReport,
        final_config: Dict[str, Any],
    ) -> List[QualityValidationResult]:
        """Validate all applied fixes.

        Pipeline order:
        1. n8n schema validation (blocking for known node types, warning-only for unknown)
        2. Cross-signal / heuristic / LLM validation per fix
        """
        results: List[QualityValidationResult] = []

        # Step 1: n8n schema validation on the final config nodes
        self._run_n8n_schema_validation(applied_fixes, final_config)

        # Step 2: Per-fix cross-signal validation
        for fix in applied_fixes:
            result = self.validate(fix, original_report)

            # Attach any n8n schema warnings to the validation details
            schema_warnings = self._n8n_schema_warnings.get(fix.fix_id, [])
            if schema_warnings:
                result.details["n8n_schema_warnings"] = schema_warnings

            # For known node types with invalid keys, fail the validation
            schema_failures = self._n8n_schema_failures.get(fix.fix_id)
            if schema_failures is not None:
                result.success = False
                result.details["schema_validation_failed"] = True
                result.details["invalid_keys"] = schema_failures

            results.append(result)

        return results

    def _run_n8n_schema_validation(
        self,
        applied_fixes: List[QualityAppliedFix],
        final_config: Dict[str, Any],
    ) -> None:
        """Run n8n schema validation on applied fixes.

        For known node types, schema violations are blocking: the corresponding
        per-fix QualityValidationResult will have success=False.
        For unknown node types, warnings are informational only.
        """
        self._n8n_schema_warnings: Dict[str, List[str]] = {}
        self._n8n_schema_failures: Dict[str, List[str]] = {}

        # Build a map of node_id -> node_type from the final config
        node_type_map: Dict[str, str] = {}
        for node in final_config.get("nodes", []):
            node_id = node.get("id", node.get("name", ""))
            node_type_map[node_id] = node.get("type", "")

        for fix in applied_fixes:
            # Determine the node type for this fix's target
            node_type = node_type_map.get(fix.target_component, "")
            if not node_type:
                continue

            # Extract changes: diff between original and modified state parameters
            changes = self._extract_fix_changes(fix)
            if not changes:
                continue

            schema_result = validate_fix_against_n8n_schema(changes, node_type)
            if not schema_result.valid:
                # Known node type with invalid keys -- blocking failure
                invalid_key_names = schema_result.invalid_keys or []
                self._n8n_schema_failures[fix.fix_id] = invalid_key_names
                warnings = schema_result.warnings.copy()
                if invalid_key_names:
                    warnings.append(
                        f"Invalid parameter keys: {', '.join(invalid_key_names)}"
                    )
                self._n8n_schema_warnings[fix.fix_id] = warnings
                for w in warnings:
                    logger.warning(f"n8n schema validation [{fix.fix_id}]: {w}")
            elif schema_result.warnings:
                # Unknown node type or informational warnings -- non-blocking
                self._n8n_schema_warnings[fix.fix_id] = schema_result.warnings
                for w in schema_result.warnings:
                    logger.warning(f"n8n schema validation [{fix.fix_id}]: {w}")

    @staticmethod
    def _extract_fix_changes(fix: QualityAppliedFix) -> Dict[str, Any]:
        """Extract the parameter changes between original and modified state."""
        changes: Dict[str, Any] = {}
        original_nodes = {
            n.get("id", n.get("name", "")): n
            for n in fix.original_state.get("nodes", [])
        }
        modified_nodes = {
            n.get("id", n.get("name", "")): n
            for n in fix.modified_state.get("nodes", [])
        }

        target = fix.target_component
        orig_params = original_nodes.get(target, {}).get("parameters", {})
        mod_params = modified_nodes.get(target, {}).get("parameters", {})

        # Find keys that were added or changed
        for key, value in mod_params.items():
            if key not in orig_params or orig_params[key] != value:
                changes[key] = value

        return changes

    def _cross_signal_validate(
        self,
        applied_fix: QualityAppliedFix,
        original_report: QualityReport,
    ) -> QualityValidationResult:
        """Use a different signal than what generated the fix."""
        generation_method = getattr(applied_fix, "generation_method", "heuristic")

        if generation_method == "heuristic":
            # Heuristic fix → validate with LLM if available, else structural
            judge = self._get_judge()
            if judge:
                return self._llm_validation(applied_fix, original_report)
            return self._structural_validation(applied_fix, original_report)
        else:
            # LLM fix → validate with structural checks + heuristic re-score
            structural = self._structural_validation(applied_fix, original_report)
            if structural.success:
                # Also run heuristic re-score as secondary check
                heuristic = self._heuristic_validation(applied_fix, original_report)
                # Both must agree
                return QualityValidationResult(
                    success=structural.success and heuristic.success,
                    dimension=applied_fix.dimension,
                    before_score=heuristic.before_score,
                    after_score=heuristic.after_score,
                    improvement=heuristic.improvement,
                    details={
                        "validation_method": "cross_signal_structural_plus_heuristic",
                        "structural_passed": structural.success,
                        "heuristic_passed": heuristic.success,
                        **structural.details,
                    },
                )
            return structural

    def _heuristic_validation(
        self,
        applied_fix: QualityAppliedFix,
        original_report: QualityReport,
    ) -> QualityValidationResult:
        """Re-run heuristic quality assessment and compare dimension scores."""
        assessor = self._get_assessor()
        new_report = assessor.assess_workflow(applied_fix.modified_state)

        dimension = applied_fix.dimension
        before_score = self._find_dimension_score(original_report, dimension)
        after_score = self._find_dimension_score(new_report, dimension)
        improvement = after_score - before_score

        return QualityValidationResult(
            success=after_score > before_score,
            dimension=dimension,
            before_score=before_score,
            after_score=after_score,
            improvement=improvement,
            details={
                "validation_method": "heuristic_reassessment",
                "overall_before": original_report.overall_score,
                "overall_after": new_report.overall_score,
                "overall_improvement": new_report.overall_score - original_report.overall_score,
            },
        )

    def _structural_validation(
        self,
        applied_fix: QualityAppliedFix,
        original_report: QualityReport,
    ) -> QualityValidationResult:
        """Validate fix using structural checks (no scoring algorithm)."""
        checks = []
        details = {"validation_method": "structural"}

        original = applied_fix.original_state
        modified = applied_fix.modified_state

        # Check 1: Config actually changed
        config_changed = original != modified
        checks.append(config_changed)
        details["config_changed"] = config_changed

        # Check 2: For prompt-based fixes, verify prompt was modified
        dimension = applied_fix.dimension
        if dimension in ("role_clarity", "output_consistency"):
            orig_prompts = self._extract_all_prompts(original)
            mod_prompts = self._extract_all_prompts(modified)
            prompt_changed = orig_prompts != mod_prompts
            checks.append(prompt_changed)
            details["prompt_changed"] = prompt_changed

            # Check prompt didn't get shorter (fixes should add, not remove)
            orig_total_len = sum(len(p) for p in orig_prompts.values())
            mod_total_len = sum(len(p) for p in mod_prompts.values())
            prompt_grew = mod_total_len >= orig_total_len
            checks.append(prompt_grew)
            details["prompt_grew"] = prompt_grew
            details["prompt_length_delta"] = mod_total_len - orig_total_len

        # Check 3: For node-adding fixes, verify new nodes are connected
        if dimension in ("observability", "agent_coupling", "best_practices"):
            orig_nodes = set(n.get("id", n.get("name", "")) for n in original.get("nodes", []))
            mod_nodes = set(n.get("id", n.get("name", "")) for n in modified.get("nodes", []))
            new_nodes = mod_nodes - orig_nodes
            if new_nodes:
                # Check at least one new node is referenced in connections
                any_connected = False
                for src, conn_data in modified.get("connections", {}).items():
                    for output_groups in conn_data.values():
                        for group in output_groups:
                            for conn in group:
                                if conn.get("node") in new_nodes:
                                    any_connected = True
                                    break
                            if any_connected:
                                break
                        if any_connected:
                            break
                    if any_connected:
                        break
                checks.append(any_connected)
                details["new_nodes"] = list(new_nodes)
                details["new_nodes_connected"] = any_connected

        # Check 4: JSON validity (modified config is parseable)
        try:
            import json
            json.dumps(modified)
            checks.append(True)
            details["json_valid"] = True
        except (TypeError, ValueError):
            checks.append(False)
            details["json_valid"] = False

        success = all(checks) if checks else False
        before_score = self._find_dimension_score(original_report, dimension)

        return QualityValidationResult(
            success=success,
            dimension=dimension,
            before_score=before_score,
            after_score=before_score + (0.05 if success else 0.0),  # Estimated
            improvement=0.05 if success else 0.0,
            details=details,
        )

    def _behavioral_validate(self, fix, original_config, modified_config, quality_report) -> bool:
        """Re-score the modified config and check if the target dimension improved."""
        try:
            from .. import QualityAssessor
            assessor = QualityAssessor(use_llm_judge=None)
            new_report = assessor.assess_workflow(modified_config)
            old_score = self._find_dimension_score(quality_report, fix.dimension)
            new_score = self._find_dimension_score(new_report, fix.dimension)
            return new_score > old_score
        except Exception:
            return True  # If re-scoring fails, don't block the fix

    def _llm_validation(
        self,
        applied_fix: QualityAppliedFix,
        original_report: QualityReport,
    ) -> QualityValidationResult:
        """Use LLM judge to independently evaluate fix quality."""
        judge = self._get_judge()
        dimension = applied_fix.dimension
        before_score = self._find_dimension_score(original_report, dimension)

        if not judge:
            # Fall back to structural if LLM unavailable
            return self._structural_validation(applied_fix, original_report)

        # Extract before/after prompts for comparison
        orig_prompts = self._extract_all_prompts(applied_fix.original_state)
        mod_prompts = self._extract_all_prompts(applied_fix.modified_state)

        # Build comparison prompt
        prompt = (
            f"Compare these two versions of an agent configuration and determine "
            f"if the second version is genuinely better for the '{dimension}' dimension.\n\n"
            f"BEFORE:\n{self._summarize_config(applied_fix.original_state)}\n\n"
            f"AFTER:\n{self._summarize_config(applied_fix.modified_state)}\n\n"
            f"Score the AFTER version from 0.0 to 1.0 for '{dimension}'.\n"
            f"A score > {before_score:.2f} means the fix improved quality.\n"
            f"Be skeptical: keyword stuffing or checkbox enabling without substance should NOT score high.\n\n"
            f'Respond ONLY with valid JSON: {{"score": <float>, "reasoning": "<explanation>"}}'
        )

        result = judge.judge(eval_type=None, output="", custom_prompt=prompt)
        after_score = result.score
        improvement = after_score - before_score

        return QualityValidationResult(
            success=after_score > before_score,
            dimension=dimension,
            before_score=before_score,
            after_score=after_score,
            improvement=improvement,
            details={
                "validation_method": "llm_judge",
                "llm_reasoning": result.reasoning,
                "llm_confidence": result.confidence,
                "llm_tokens": result.tokens_used,
            },
        )

    @staticmethod
    def _find_dimension_score(report: QualityReport, dimension: str) -> float:
        """Find score for a dimension in a quality report."""
        for agent in report.agent_scores:
            for dim in agent.dimensions:
                if dim.dimension == dimension:
                    return dim.score
        for dim in report.orchestration_score.dimensions:
            if dim.dimension == dimension:
                return dim.score
        return 0.0

    @staticmethod
    def _extract_all_prompts(config: Dict[str, Any]) -> Dict[str, str]:
        """Extract all system prompts from a workflow config."""
        prompts = {}
        for node in config.get("nodes", []):
            params = node.get("parameters", {})
            for key in ("systemMessage", "systemPrompt", "system", "text"):
                val = params.get(key) or params.get("options", {}).get(key)
                if val and isinstance(val, str):
                    node_id = node.get("id", node.get("name", "unknown"))
                    prompts[node_id] = val
        return prompts

    @staticmethod
    def _summarize_config(config: Dict[str, Any]) -> str:
        """Create a concise summary of a workflow config for LLM evaluation."""
        parts = []
        for node in config.get("nodes", [])[:5]:
            name = node.get("name", "?")
            node_type = node.get("type", "?")
            params = node.get("parameters", {})
            prompt = params.get("systemMessage", params.get("systemPrompt", ""))
            prompt_preview = prompt[:150] + "..." if len(prompt) > 150 else prompt
            options = params.get("options", {})

            part = f"Node: {name} ({node_type})"
            if prompt_preview:
                part += f"\n  Prompt: {prompt_preview}"
            if options:
                part += f"\n  Options: {options}"
            if node.get("continueOnFail"):
                part += "\n  continueOnFail: true"
            parts.append(part)

        connections = config.get("connections", {})
        parts.append(f"Connections: {len(connections)} source nodes")
        return "\n".join(parts)
